"""update limits

Revision ID: 6e21fdaa06f7
Revises: 
Create Date: 2022-12-22 12:47:08.060795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e21fdaa06f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=1000),
               nullable=True)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=1000),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1000),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('lastName',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('firstName',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###
